import type { Metadata } from 'next';
import { Anton } from 'next/font/google';
import './globals.css';

const anton = Anton({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App This is Main Layout',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={anton.className}>
        <div className="text-center">
          <div className="m-5">Navbar For Main Layout</div>
          <div>{children}</div>
          <div className="m-5">Footer For Main Layout</div>
        </div>
      </body>
    </html>
  );
}
