import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Login Page',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="text-red-500">Nav bar For login page</div>
      <div>{children}</div>
      <div className="text-red-500">Footer For login page</div>
    </div>
  );
}
